### ISSUE TITLE
Pas de propriété id ? 

### ISSUE THREAD

**Issue by matcaps** [jcalise6891/Logitud_SkiChampionShip#1]
https://github.com/jcalise6891/Logitud_SkiChampionShip/blob/ebd652842c6ab660a19213de8ab44955f14c6766/src/Entity/Profil.php#L14

**Comment by jcalise6891** [comment]
> https://github.com/jcalise6891/Logitud_SkiChampionShip/blob/ebd652842c6ab660a19213de8ab44955f14c6766/src/Entity/Profil.php#L14

Ajouté lors du commit  20

https://github.com/jcalise6891/Logitud_SkiChampionShip/blob/97a300a62c1982c6dce3cb50f2ef8520f5a4792c/src/Entity/Profil.php#L14
